apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: codestate
    tier: frontend
  name: userapi
  selfLink: /apis/extensions/v1beta1/namespaces/k8sdemo/deployments/userapi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: codestate
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: codestate
        tier: frontend
    spec:
      containers:
      - image: codestate:v1
        imagePullPolicy: IfNotPresent
        name: userapi
        env:
        - name: DATA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: dataservice-config
              key: DATA_SERVICE_URL
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}